[theme]
base="dark"
primaryColor="#00ADB5"
backgroundColor="#1E1E1E"
secondaryBackgroundColor="#2C2C2C"
textColor="#FFFFFF"
font = "Lato:https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap, Source Sans Pro, sans-serif"